### ISSUE TITLE
Sample Project?

### ISSUE THREAD

**Issue by davegi** [JohnnyHendriks/TestAdapter_Catch2#1]
I've been trying to get this adapter working, by tweaking the _.runsettings_ file, but have yet to get it to even list the `TEST_CASE`  in the Test Explorer. TE is showing MS-Test test cases in the same DLL.

This is the test file:
```C++
#include "stdafx.h"
//#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

unsigned int Factorial(unsigned int number) {
	return number <= 1 ? number : Factorial(number - 1)*number;
}

TEST_CASE("Factorials are computed", "[factorial]") {
	REQUIRE(Factorial(1) == 1);
	REQUIRE(Factorial(2) == 2);
	REQUIRE(Factorial(3) == 6);
	REQUIRE(Factorial(10) == 3628800);
}
```
So, by chance can you post a fully working / configured Project that successfully uses your Adapter?

Thanks,
djg

**Comment by JohnnyHendriks** [comment]
I was actually working on the v1.1.0 release. Based on your problem I added a Walkthrough for v1.1.0, that hopefully will help you with your problem.
 
[Walkthrough](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Walkthrough.md)

Thank you for trying the adapter.

**Comment by davegi** [comment]
Thanks for the quick reply. W/your walkthrough I was able to build/run the UTs for the ReferenceTests Solution…next I’ll take some time to understand the nuance’s of the settings and then implement some of my own tests!

Just wanted to let you know that although the tests built/run, 31/59 failed…many due to, e.g.,:

Test Name:         NoSEH.Tests01. 01f Null dereference
Test FullName:   NoSEH.Tests01. 01f Null dereference
Test Source:       c:\users\daveg\documents\visual studio 2017\projects\brendonoply\testadapter_catch2\referencetests\src\catch2\catch_noseh\ut_tests01.cpp : line 37
Test Outcome:   Failed
Test Duration:    0:00:00

Result Message:
Invalid test runner output.
-------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<Catch name="Catch_NoSEH.exe">
  <Group name="Catch_NoSEH.exe">
    <TestCase name="NoSEH.Tests01. 01f Null dereference" tags="[failing]" filename="c:\users\daveg\documents\visual studio 2017\projects\brendonoply\testadapter_catch2\referencetests\src\catch2\catch_noseh\ut_tests01.cpp" line="37">
-------------------------------------------------------------------------------

Also, out of curiosity why isn’t the default to use custom test discovery, so that the stack trace is (always) available?

Thanks again,
djg

**Comment by JohnnyHendriks** [comment]
Good to hear you were able to get it to work.

### Failing tests
It is correct that out of 59 tests 31 fail and 1 test is skipped. This is by design for these tests, as part of the purpose of these tests is to see what happens when a test fails (or hangs in case of the skipped test). A handful of tests even fail so badly that the adapter cannot process the output that is generated, in which case the bad raw output is part of the message so you have at least that to help you find out what the problem is.

Note that all tests in Catch_NoSEH produce bad output. For these tests Structured Exception Handling by Catch2 is turned off (it is on by default, but for some code bases this needs to be turned off). The equivalent tests with SEH turned on are located in Catch_Testset03 Testset03.Tests05. There correct output is generated. These are special cases that the majority of people should not encounter.

### Reason for not making custom discovery default
The reason for not making custom discovery the default is that it currently requires you to implement your Catch2 unit tests with a custom discovery mechanism. I assume a significant number of people are not willing or allowed to do this for their tests. This will be re-evaluated if/once Catch2 starts to support an appropriate discovery mechanism for the test adapter out of the box.

**Comment by davegi** [comment]
Hey Johnny--
Starting with the `.runsettings` file from the  ReferenceTests Solution, and making only the following edit:
``` XML
    <!--<FilenameFilter>^Catch_</FilenameFilter>-->
    <FilenameFilter>.*</FilenameFilter>
```
I am still unable to discover/run the TEST_CASE documented above.
Thoughts?
djg

**Comment by JohnnyHendriks** [comment]
I'm not able to reproduce the problem. The following works for me. If the problem persists, set `<Logging>verbose</Logging>` and look at the Tests output. Compare with the output described on the Walkthrough page.

### Very Basic Example
main.cpp
```
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

unsigned int Factorial(unsigned int number) {
    return number <= 1 ? number : Factorial(number - 1)*number;
}

TEST_CASE("Factorials are computed", "[factorial]") {
    REQUIRE(Factorial(1) == 1);
    REQUIRE(Factorial(2) == 2);
    REQUIRE(Factorial(3) == 6);
    REQUIRE(Factorial(10) == 3628800);
}
```
VeryBasic.runsettings
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>

  <!-- Catch2 adapter -->
  <Catch2Adapter>
    <DiscoverCommandLine>--list-tests *</DiscoverCommandLine>
    <FilenameFilter>.*</FilenameFilter>
  </Catch2Adapter>

</RunSettings>
```

### With custom discovery
main.cpp
```
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

void Discover(Catch::Session& session);

int main(int argc, char* argv[])
{
    Catch::Session session;

    bool doDiscover = false;

    // Add option to commandline
    {
        using namespace Catch::clara;

        auto cli = session.cli()
            | Opt(doDiscover)
            ["--discover"]
        ("Perform VS Test Adaptor discovery");

        session.cli(cli);
    }

    // Process commandline
    int returnCode = session.applyCommandLine(argc, argv);
    if (returnCode != 0) return returnCode;

    // Check if custom discovery needs to be performed
    if (doDiscover)
    {
        try
        {
            Discover(session);
            return 0;
        }
        catch (std::exception& ex)
        {
            Catch::cerr() << ex.what() << std::endl;
            return Catch::MaxExitCode;
        }
    }

    // Let Catch2 do its thing
    return session.run();
}

void Discover(Catch::Session& session)
{
    using namespace Catch;

    // Retrieve testcases
    const auto& config = session.config();
    auto testspec = config.testSpec();
    auto testcases = filterTests(Catch::getAllTestCasesSorted(config)
        , testspec
        , config);

    // Setup reporter
    TestRunInfo runInfo(config.name());

    auto pConfig = std::make_shared<Config const>(session.configData());
    auto reporter = getRegistryHub()
        .getReporterRegistry()
        .create("xml", pConfig);

    Catch::Totals totals;

    reporter->testRunStarting(runInfo);
    reporter->testGroupStarting(GroupInfo(config.name(), 1, 1));

    // Report test cases
    for (const auto& testcase : testcases)
    {
        Catch::TestCaseInfo caseinfo(testcase.name
            , testcase.className
            , testcase.description
            , testcase.tags
            , testcase.lineInfo);
        reporter->testCaseStarting(caseinfo);
        reporter->testCaseEnded(Catch::TestCaseStats(caseinfo
            , totals
            , ""
            , ""
            , false));
    }

    reporter->testGroupEnded(Catch::GroupInfo(config.name(), 1, 1));
    TestRunStats testrunstats(runInfo, totals, false);
    reporter->testRunEnded(testrunstats);
}

unsigned int Factorial(unsigned int number) {
    return number <= 1 ? number : Factorial(number - 1)*number;
}

TEST_CASE("Factorials are computed", "[factorial]") {
    REQUIRE(Factorial(1) == 1);
    REQUIRE(Factorial(2) == 2);
    REQUIRE(Factorial(3) == 6);
    REQUIRE(Factorial(10) == 3628800);
}
```

CustomDiscover.runsettings
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>

  <!-- Catch2 adapter -->
  <Catch2Adapter>
    <DiscoverCommandLine>--discover *</DiscoverCommandLine>
    <FilenameFilter>.*</FilenameFilter>
  </Catch2Adapter>

</RunSettings>
```
Note: with the CustomDiscover.runsettings the Very Basic test is not found.

**Comment by davegi** [comment]
OK…I was able to get both of your samples working! Additionally, here’s what I’ve discovered so far…
- I was building a DLL w/`CATCH_CONFIG_RUNNER` defined
- You (I'm guessing) built an EXE w/:
-- Very Basic Example (VBE): `CATCH_CONFIG_MAIN` defined
-- With Custom Discovery (WCD): `CATCH_CONFIG_RUNNER` defined

I misunderstood the meaning of the two `defines`. I thought the `CATCH_CONFIG_RUNNER` was needed when creating a DLL (i.e., no `main()`).

The adapter does not discover any tests when built as a DLL w/either `define`s (!).

Also, I noticed that in the VBE the runsettings file contained:
- `<DiscoverCommandLine>--list-tests *</DiscoverCommandLine>`

Whereas the one for WCD contains:
- `<DiscoverCommandLine>--discover *</DiscoverCommandLine>`

I missed the difference the first time through.

Thanks for very quick replies and assistance,
djg

**Comment by JohnnyHendriks** [comment]
I'm glad to hear the reason for the problems has been found. It's always in the details.

It is true that the Test Adapter only discovers tests in EXE files. If you want the tests to be in a DLL you also have to create an EXE that passes Catch2 commandline parameters to the entry-point in the DLL. As far as I'm aware the Catch2 framework is intended to be used via an EXE not a DLL. I haven't thought about supporting discovering tests through a DLL. I might explore that possibility in the future, though I'm not sure if this is something that can be easily supported.
