### ISSUE TITLE
Printing to stdout is broken

### ISSUE THREAD

**Issue by anders-burov** [JohnnyHendriks/TestAdapter_Catch2#10]
None of the characters written with `printf` or `std::cout << ` show up in the output window. Also the usual Visual Studio console that is invoked when console application is running is suppressed. Is there a way to get the stdout working? So far I have been using MessageBoxes, but it's not that convenient for logging.

**Comment by JohnnyHendriks** [comment]
Characters from `std::cout` are captured by Catch2. When run via the Test Adapter for Catch2 this output is placed behind the standard output link in the Test Case details view. See the [walkthrough](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Walkthrough.md#successful-test-with-stdcout-and-stdcerr-output) for details.

With regard to `printf`, as far as I'm aware this output is not intercepted by Catch2. However, it may interfere with the output generated by Catch2 that is used by the Test Adapter for Catch2. As a result use of `printf` may cause the Test Adapter to give a failed result on account of an invalid test result output.

Note, if you want to communicate text in a Catch2 unit test it may be better to use the `INFO`, `WARN`, or `FAIL` macros, that is what they are there for. Note `INFO` text is only displayed when a test fails, `WARN` text is always shown but does not fail the test, `FAIL` always shows the text but also fails the test.
