### ISSUE TITLE
Running from commandline

### ISSUE THREAD

**Issue by sdaly2107** [JohnnyHendriks/TestAdapter_Catch2#14]
Hi

I have this set up and working from the test explorer in VS, but struggling to get it to work from the commandline with vstest.console.exe.

I'm running the following - 
vstest.console.exe Test.exe /Settings:catch.runsettings

"No test is available in Test.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>."

Any help is appreciated! :)

**Comment by sdaly2107** [comment]
I think I need to specify /TestAdapterPath to the catch2 adapter, but where is this located?

**Comment by sdaly2107** [comment]
Ignore me, I built the adapter from source and used the following - 

vstest.console.exe  "Test.exe" /TestAdapterPath:c:\Catch2Adapter /Settings:c:\catch2adapter\catch.runsettings /InIsolation

**Comment by JohnnyHendriks** [comment]
Good to know it also works from the commandline. It is one of the many things that is still on my to do list.
