### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by iwubcode** [JohnnyHendriks/TestAdapter_Catch2#15]
Would love to use this for the next latest and greatest Visual Studio!

EDIT: When searching, I was not able to find it in the market-place.  So my assumption is it currently isn't supported.

**Comment by iwubcode** [comment]
Looks like it's pretty easy to do:  https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by JohnnyHendriks** [comment]
Thank you for the suggestion.

I would love to use it too for the next latest and greatest Visual Studio, just hadn't gotten around to setting up the VS2019 Preview yet to make sure the Test Adapter works there. But that's now done and everything seems to work fine. So the update should now be available and usable in VS2019.

**Comment by iwubcode** [comment]
Thanks @JohnnyHendriks for the speedy solution.  I'll give it a whirl!
