### ISSUE TITLE
Default discovery with test case file/line info using Catch2 --list-tests --verbosity high

### ISSUE THREAD

**Issue by abdes** [JohnnyHendriks/TestAdapter_Catch2#18]
Currently we can jump into the test cases source code only when using the XML custom discovery method. However, catch2 has added, since a while now, a command line option to the standard test runner "--verbosity high" that would generate the file/line info for test cases when listing them with --list-tests.

To avoid the need for custom discoverer, catch2 test adapter can simply support parsing such additional info with the default discovery method.

Here is an example of the output **without** '--verbosity high':

```
All available test cases:
  TestAssertion
      [assert][common]
  TestLoggable
      [common][logging]
  TestMultipleThreads
      [common][logging]
  TestLogWithPrefix
      [common][logging]
  TestLogPushSink
      [common][logging]
5 test cases
```

and this is **with** the '--verbosity high':

```
All available test cases:
  TestAssertion
    e:\dev\projects\asap_repos\asap\common\test\assert_test.cpp(13)
    (NO DESCRIPTION)
      [assert][common]
  TestLoggable
    e:\dev\projects\asap_repos\asap\common\test\logging_test.cpp(55)
    (NO DESCRIPTION)
      [common][logging]
  TestMultipleThreads
    e:\dev\projects\asap_repos\asap\common\test\logging_test.cpp(69)
    (NO DESCRIPTION)
      [common][logging]
  TestLogWithPrefix
    e:\dev\projects\asap_repos\asap\common\test\logging_test.cpp(108)
    (NO DESCRIPTION)
      [common][logging]
  TestLogPushSink
    e:\dev\projects\asap_repos\asap\common\test\logging_test.cpp(157)
    (NO DESCRIPTION)
      [common][logging]
5 test cases
```

**Comment by JohnnyHendriks** [comment]
I was not aware of this possibility. Thank you for making me aware. I will add support for this option.

**Comment by JohnnyHendriks** [comment]
The feature has been added in the v1.5.0 release. Again, thank you for suggesting this.

**Comment by abdes** [comment]
@JohnnyHendriks thanks for the update. I got it and using it right now. I just wanna point out to you that for certain test cases in the discovered list in the VS UI, although the test case properties show the correct source file and the correct line number, double clicking on the test case only goes to the top of the source file and not to the exact line of the test case.

This only happens for some test cases and not for the others.
