### ISSUE TITLE
Fix --discover in ReferenceTests.runsettings

### ISSUE THREAD

**Issue by brdann** [JohnnyHendriks/TestAdapter_Catch2#2]
Hello! Thank you for developping this! There is a problem with tests discovery in ReferenceTests.runsettings which is linked from Walkthrough.md (change --discover to --list-tests).

**Edit:** Okay, I'm starting to realize that is probably intentional to demonstrate a custom discovery mechanism. But don't link that file in walkthrough -- it's confusing.

**Comment by JohnnyHendriks** [comment]
Thank you for the feedback. Indeed the intension was to demonstrate what the advantage is of a custom discover. I updated the Walkthrough in an attempt to make it more clear. Also added a Minimal.runsettings file to the walkthrough to help with this.
