### ISSUE TITLE
VS2019 Unable to discover Tests

### ISSUE THREAD

**Issue by Bluesman74** [JohnnyHendriks/TestAdapter_Catch2#22]
First thanks for the update to support VS2019 for your Extension.  Its much appreciated.

I initially had weird warnings in the Tests output due to having both GoogleTest and BOOSTTest Test Runner extensions, which are gone now that I have removed both.

Then I tried to discover the tests without a .runsettings file, as I thought I had read that this is no longer a requirement.

However when that didn't work I  first tried a ".runsettings" file and then one with the same prefix as my executable name, but both times I got Identical errors.
```
[18/03/2019 16:31:32 Informational] ------ Discover test started ------
[18/03/2019 16:31:33 Error] Catch2 Test Adapter Settings not found, Catch2 test discovery is cancelled. Add Catch2Adapter settings to runsettings-file.
[18/03/2019 16:31:33 Warning] No test is available in C:\Users\MyUser\VisualStudio Projects\Visual Studio 2019\Projects\C++\TupleTest\Debug\TupleTest.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[18/03/2019 16:31:33 Informational] ========== Discover test finished: 0 found (0:00:01.3020027) ==========
```

Peter

**Comment by Bluesman74** [comment]
I used the contents I found in the Wiki for my .runsettings files:

<?xml version="1.0" encoding="utf-8"?>
```
<RunSettings>

    <!-- Adapter Specific sections -->
    <Catch2Adapter>
        <DebugBreak>on</DebugBreak><!-- Introduced in v1.1.0 -->
        <DiscoverCommandLine>--verbosity high --list-tests *</DiscoverCommandLine>
        <DiscoverTimeout>500</DiscoverTimeout><!-- Milliseconds -->
        <FilenameFilter>^Catch_</FilenameFilter><!-- Regex filter -->
        <IncludeHidden>true</IncludeHidden>
        <Logging>normal</Logging>
        <MessageFormat>StatsOnly</MessageFormat>
        <StackTraceFormat>ShortInfo</StackTraceFormat>
        <StackTracePointReplacement>,</StackTracePointReplacement><!-- Introduced in v1.3.0 -->
        <TestCaseTimeout>20000</TestCaseTimeout><!-- Milliseconds -->
        <WorkingDirectory>..\TestData</WorkingDirectory>
        <WorkingDirectoryRoot>Executable</WorkingDirectoryRoot>
    </Catch2Adapter>

</RunSettings>
```

**Comment by JohnnyHendriks** [comment]
You still need the .runsettings file, but only the `<FilenameFilter>` is required. What is new is that by default you now also get a source link to the test case (before you needed a custom discovery mechanism to get this feature).

As a sanity check, did you actually select the .runsettings file? In the menu `Test` > `Test Settings` > there should be a checkmark next to the .runsettings file that was selected. Note that clicking it actually toggles the checkmark, so do not click it if the checkmark is there. If there is no .runsettings file listed select one with the `Select Test Settings File` option.

**Comment by Bluesman74** [comment]
Hi,

Thanks Johnny, the tests are now getting discovered.
