### ISSUE TITLE
Run Selected Tests doesn't quote names with spaces

### ISSUE THREAD

**Issue by melak47** [JohnnyHendriks/TestAdapter_Catch2#26]
In VS2019, when running test cases from the test explorer (both individually, and "Run All"),
It appears the extension invokes the test executable with the test names unquoted.
So if you have a `TEST_CASE("foo works")` for example, the extensions then runs `tests foo works` (which would run the test cases `foo` and `works`, but not `foo works`).

The test names should be quoted so that `tests "foo works"` is invoked, for example.

As a side note, the test cases are marked as passing, even though the output says "no tests ran".
The arguments `-w NoTests` could be used to turn that into a warning at least -- maybe it should be an error, but a warning is still better than silently passing.

**Comment by JohnnyHendriks** [comment]
This is a bit odd, as quotes are added around the exact testcase name provided. In case of long testcase names there is potentially a problem when using multiple spaces in a row. Also, having test case names with names that only differ in case are a potential problem. See the [Notes on test case names](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Capabilities.md#notes-on-test-case-names) for more information.

Also, in case a test was not run it should show up as skipped. As such I would need more information to help with your problem, but my first guess is that you have conflicting test case names somewhere. Though I'm pretty sure that case would have been warned about in the test result message. But that is easily missed, especially in case the test result returns as passed.

**Comment by melak47** [comment]
There is only one test case.
![image](https://user-images.githubusercontent.com/3340026/59580783-cb4f1400-90d2-11e9-96c0-33bd1818ea40.png)
I added a sleep at global scope so I could easily check the process being launched, and its command-line looks like this:
```
"D:\temp\out\build\x64-Debug\test_sample.exe" foo works
```

Here is the [sample project](https://github.com/JohnnyHendriks/TestAdapter_Catch2/files/3295396/repro.zip) I used. I just open it in VS 2019 in "open folder" mode (Catch2 is installed via vcpkg).

**Comment by JohnnyHendriks** [comment]
That explains it. The test adapter for Catch2 does not work in Open Folder mode. It only works with Visual Studio solutions. In open folder mode the CTest adapter is used (for CMake projects), which currently does not have special support for Catch2. I've requested integration of the Test Adapter for Catch2 into the CTest adapter with Microsoft, but apparently this is not a straightforward exercise.

**Comment by melak47** [comment]
That's disappointing, yet another reason we may not be able to use Catch2 :(

**Comment by McKillroy** [comment]
Same issue when using sth like:
TEST_CASE ("Memory::ContiguousPoolAllocator::operator[]")
where the square brackets bust it
TEST_CASE ("Memory::ContiguousPoolAllocator::operator")
works with my CMake open folder project.
