### ISSUE TITLE
Custom header results in no discovered test cases

### ISSUE THREAD

**Issue by matt77hias** [JohnnyHendriks/TestAdapter_Catch2#28]
With additional prints in my test main method, no test cases are discovered.
Without additional prints in my test main method, all test cases are discovered.

Ideally, I like to output my own header.

```c++
int main(int argc, char** argv)
{
	std::cout << "Hello/n"; // No tests are discovered if not commented?
	
	// Catch setup.
	Catch::Session session;

	const int result = session.applyCommandLine(argc, argv);
	if (result != 0)
	{
		return result;
	}

	return session.run();
}
```

Minimal VS2019 example: [Widget.rar](https://www.dropbox.com/s/ktz0wh7ocsfsei8/Widget.rar?dl=0).

**Comment by matt77hias** [comment]
IIRC my Google tests disappeared at some point as well upon adding custom code to the main method (though, I did not look further). So it is possible that this is a general issue with VS2019?

**Comment by JohnnyHendriks** [comment]
Don't know about Google tests, but in the case of Catch2, for the discovery of tests a specific output from the executable is expected. As such, any additional output will interfere with the parsing of the Discovery output. This will typically result in no tests being discovered, as it is assumed the executable is not a test executable. The only way for the test adapter to know that it is dealing with a Catch2 test executable is by the output generated when a specific command is given. For more info about test discovery see the [Testcase Discovery](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Discovery.md) page.

**Comment by matt77hias** [comment]
Thanks for the info. Unfortunately, the discovery is not the only query VS uses (because it also has to evaluate tests). So it seems only safe to output additional content if only one argument is passed to the executable.

**Comment by JohnnyHendriks** [comment]
If you really want/need to output additional output under some conditions, you could always try to add a custom commandline option to enable the additional output. See the [Custom discovery example](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Discovery.md#example) for inspiration.
