### ISSUE TITLE
ReferenceTests.sln

### ISSUE THREAD

**Issue by jay-amd** [JohnnyHendriks/TestAdapter_Catch2#31]
It looks like the ReferenceTests.sln file is missing.

**Comment by JohnnyHendriks** [comment]
Thank you for mentioning this. I'm in the middle of changing some things around. I'm now using CMake to generate the reference tests. But I forgot to update the walkthrough to take into account the new situation. This is now on my list of things to do ASAP.

**Comment by jay-amd** [comment]
You’re welcome.

So you’ll still add a .sln file at some point?

**Comment by JohnnyHendriks** [comment]
New solutions have been added for use with the walkthrough. Both one for use with VS2017 and one for use with VS2019. Minimal adjustment to the walkthrough to reflect this were amde. A seperate walkthrough based on changes in the VS2019 Test Explorer are on the agenda.

**Comment by JohnnyHendriks** [comment]
Fixed the walkthrough solutions for VS2017 and VS2019. Thought I created them after moving the main.cpp file to the new location. I guess I was mistaken. My bad.
