### ISSUE TITLE
Testadapter not working when FilenameFilter contains UNDERSCORE?

### ISSUE THREAD

**Issue by jgunnars** [JohnnyHendriks/TestAdapter_Catch2#36]
I found a strange thing when using the Testadapter v1.5.1. in VisualStudio 2019 v16.4.2:
When FilternameFilter in the **.runsettings**-file has UNDERSCORES the adapter seems to fail. (In regular expressions undescores should just be taken literally and not have any special meaning.)

I tried to narrow it down: With a unit-test named "jogu_abc_UnitTest.exe":
FilenameFilter="jogu_" does NOT work.
FilenameFilter="u_" does NOT work.
FilenameFilter="_UnitTest" works.
FilenameFilter="_U" works.

When it fails the testadapter finds the file but reports "Invalid source." (When Logging=debug).

I've worked my way around it but I thought you should know!
Best Regards!
Jo

**Comment by JohnnyHendriks** [comment]
Thank you for informing me. Sorry for the late answer. Just released a new version (1.6.0) and I wasn't able to reproduce the problem there. So I'm closing the issue.
