### ISSUE TITLE
Custom PATH environment variable

### ISSUE THREAD

**Issue by zomgrolf** [JohnnyHendriks/TestAdapter_Catch2#37]
Is there a way to update the PATH environment variable used for the test executable (similar to how VS lets the user update the environment for debugging)? I have a bunch of unit tests that depend on 3rd party components, implemented as DLLs, which at the moment I have to copy to the test executable directory. I'd rather set up a custom PATH variable to let the loader find the dependencies without having to copy them.

**Comment by JohnnyHendriks** [comment]
As far as I can tell this is currently not possible. But a quick look tells me that it should be fairly easy to add this functionality. It would then be something you can set in the runsettings-file. I'll try to make it part of the next release, which I'm currently wrapping up.

**Comment by zomgrolf** [comment]
That would be awesome, thanks!

**Comment by JohnnyHendriks** [comment]
This has now been implemented in the latest release. See [Settings documentation](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#environment) on how to use it.
