### ISSUE TITLE
Description of FilenameFilter is unclear

### ISSUE THREAD

**Issue by Mike4Online** [JohnnyHendriks/TestAdapter_Catch2#38]
In [the Settings.md reference document](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Settings.md), the **FilenameFilter** setting is described as both applying to **test executables** as well as to **source files**.  This is very confusing.  It appears this filter applies to test executables only.  Please clarify the text in this document accordingly.

**Comment by JohnnyHendriks** [comment]
Thank you for reading the documentation. Some internal nomenclature seems to have leaked through here. I'm currently updating the documentation for the new version. I've made the appropriate adjustments there, which should be submitted in the near future.

**Comment by JohnnyHendriks** [comment]
Finally released the new version. Documentation has been updated.
