### ISSUE TITLE
Can't debug in visual studio

### ISSUE THREAD

**Issue by SasLuca** [JohnnyHendriks/TestAdapter_Catch2#42]
I am trying to add the ability to load catch2 dll unit tests to the plugin however I am unable to properly debug the solution in visual studio 2019.

If I put a breakpoint in TestDiscoverer.cs for example, it will appear with a warning saying "No symbols loaded for this document".

Is this a known issue or is there a specific set of actions that I need to follow in order to get debugging to work?

**Comment by JohnnyHendriks** [comment]
I've not been able to debug the Cacth2TestAdapter project directly myself as well. I also find this a very annoying situation. My workaround was to put as much functionality into the Catch2Interface project, and test that code via unit tests. Debugging those tests should then give you the ability to step through the code and set break points as usual.
