### ISSUE TITLE
Invalid Test Runner Output When Encountering Custom Logging

### ISSUE THREAD

**Issue by knogas** [JohnnyHendriks/TestAdapter_Catch2#43]
In our application, we use Boost logging throughout.  I've discovered that this does not pose a problem if running Catch on the command line, but it does when running through Visual Studio 2017's Test Explorer using TestAdapter_Catch2.

For instance, running Catch on the command line, the test output handles our logging statements:

![image](https://user-images.githubusercontent.com/72627673/101101438-d5dec100-3585-11eb-98d2-7f0ced0c6d0b.png)

If I run it through Visual Studio's Test Explorer, I get the following:

![image](https://user-images.githubusercontent.com/72627673/101103798-f22f2d80-3586-11eb-8aa2-923436c5b5e4.png)

As you can see, the logging statement caused ill-formed XML output.  I experimented by by-passing Boost logging and simply trying a printf("Test") statement and the problem persists.  Unless I format the message to fit within the XML with something like  `" MSG=\"Test\""`, I continue to get this error.

I would expect any strings or debugging statements that are encountered during a test run would be handled as Catch2 is currently doing when running on the command line.

**Comment by JohnnyHendriks** [comment]
This should already be fixed for the next version. Still working on the documentation changes for the new version though. But you could build the current master branch yourself and install that version if you want to test it now. My goal is to have the new version out before the end of the year 2020. I will give an extra push and try to finish it already this weekend.
