### ISSUE TITLE
Displaying TEST_CASE titles

### ISSUE THREAD

**Issue by BobbeYo1983** [JohnnyHendriks/TestAdapter_Catch2#44]
If I specify the name TEST_CASE ("Name 1.2.3.4.5"), then the adapter displays with some nesting. Why is this happening, which symbols cannot be used? Or is this a VS issue?

**Comment by JohnnyHendriks** [comment]
This is indeed a Visual Studio Test Explorer thing. See [Notes on test case names](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Capabilities.md#notes-on-test-case-names) for more information. In VS2019 you have a little more control over how the nesting is done though. See the following [MS docs](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019#group-and-filter-the-test-list)
