### ISSUE TITLE
Error: Unable to reconstruct long test name

### ISSUE THREAD

**Issue by bryanSME** [JohnnyHendriks/TestAdapter_Catch2#45]
I'm getting an error with long scenario values.  I created a question on StackOverflow about this.   Why is this happening? What can I do to fix it?

[catch2-unable-to-reconstruct-long-test-name](https://stackoverflow.com/questions/66531731/catch2-unable-to-reconstruct-long-test-name)

**Comment by JohnnyHendriks** [comment]
Just released the new version (v1.6.0) of the test adapter. It should be able to handle long testcase names better, but there are still corner cases where it fails. See [section on long testcase names](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Capabilities.md#long-test-case-names) in the documentation for details.
