### ISSUE TITLE
Test doesn't execute due to file being in use

### ISSUE THREAD

**Issue by iwubcode** [JohnnyHendriks/TestAdapter_Catch2#46]
I see the following error when running some of my tests:

```
An exception occurred while invoking executor 'execturo://catch2testexecutor/': The process cannot access the file '/path/to/file/.exe.report.<id>.xml' because it is being used by another process
```

I don't see these files being used in resource monitor so I'm not sure what other process could be the conflict.

The callstack isn't too helpful, here are the last few lines:

```
System.IO.__Error.WinIOError(In32 errorCode, String maybeFullPath)
System.IO.File.InternalDelete(String path, Boolean checkHost)
Catch2Interface.Executor.Run(string testname, String source)
```

**Comment by JohnnyHendriks** [comment]
Thank you for reporting this. The way things work is that a process is created for the test executable, which is asked to create a report in xml-format and save it to a file. After the process is done, or forcibly closed, this file is read to extract the test results. After that the file is deleted. It appears something goes wrong with this last step. To circumvent this problem you can set the [Logging-parameter](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#logging) to Debug. In this case there should be no attempt to delete the file.

I have never seen this error myself, so I don't know how to reproduce. But I will try to make a modification to prevent this from happening and hope that this works. The only thing I can think of now as to why the file cannot be accessed is that a virus-scanner may have taken possession of it for scanning, but this is just a wild guess. Or that the test-executable crashed in a way that it closed the processes but not the report file.

**Comment by iwubcode** [comment]
Thanks!  I'll try that debug flag.

I took a quick look at the code and noticed a couple things:

* When the process [isn't forcibly killed](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Libraries/Catch2Interface/Executor.cs#L187), we never call Close() on the process.  But `Process.WaitForExit()` [says](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-5.0):

>  The system is aware of handles to exited processes that have not been released by Process components, so it keeps the ExitTime and Handle information in memory until the Process component specifically frees the resources. For this reason, any time you call Start for a Process instance, call Close when the associated process has terminated and you no longer need any administrative information about it. Close frees the memory allocated to the exited process.

(not sure if that would impact file handles owned by the process)

* In `ReadReport()` the `FileShare` [attribute is being used](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Libraries/Catch2Interface/Executor.cs#L345) but it may be useful to wrap the stream in a [using statement](https://stackoverflow.com/questions/26741191/ioexception-the-process-cannot-access-the-file-file-path-because-it-is-being) to be safe.  If there is an exception that should ensure that the stream is still closed.  I think you also want to do this for the file as well.

**Comment by JohnnyHendriks** [comment]
Just released a new version that should fix this problem.
