### ISSUE TITLE
allow runsettings that will pass arguments

### ISSUE THREAD

**Issue by obi0ne** [JohnnyHendriks/TestAdapter_Catch2#48]
when running from executable (not via test explorer),
I'm able to set command arguments, in such way that they can filter specific test by TAGS.

I wish to have similar ability within this adapter.
Can you allow some settings that will allow to "tunnel" the setting, in such way, that if I have tag filter, clicking run, will just execute the related tests...

**Comment by JohnnyHendriks** [comment]
You need to configure the [`<DiscoverCommandLine>`](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#discovercommandline) setting for that. Default value is `--verbosity high --list-tests *` but you could set it to `--verbosity high --list-tests [YourTag]` in which case only tests with the `[YourTag]`-tag will be shown in the TestExplorer. You can create different runsettings-files for different discovery-profiles to be able to switch between them easily in the TestExplorer.
