### ISSUE TITLE
Infinite search during test discovery

### ISSUE THREAD

**Issue by ngzaharias** [JohnnyHendriks/TestAdapter_Catch2#49]
the following code will cause test detection to infinite loop, I assume it is because of the system("pause")
(for those curious, I added it before I was using the test adaptor so that I could see the results after running the project)

```
#define CATCH_CONFIG_RUNNER
#include <Catch2/catch.hpp>
int main(int argc, char* argv[]) 
{
	const int result = Catch::Session().run(argc, argv);
	system("pause");
	return result;
}	
```
replacing it with the following made it work
```
#define CATCH_CONFIG_RUNNER
#include <Catch2/catch.hpp>

int main(int argc, char* argv[]) 
{
	Catch::Session session;
	session.applyCommandLine(argc, argv);
	return session.run();
}	
```

**Comment by JohnnyHendriks** [comment]
Thank you for your comment. I was not aware of this. That being said, I don't see a way to workaround this problem. Somehow the `system("pause")` command bypasses the timeout mechanism for running a processes from C#. All I can suggest is, to not make use of `system("pause")`, but you already figured that out. You can always mimic the functionality via the use of a bat-file that calls the executable and then calls pause. Reading up on the use of `system("pause")` I also found that its use is frowned upon for understandable reasons. As such I will not put more effort in trying to fix this.

**Comment by ngzaharias** [comment]
Coming to this very late, but I just ran into this exact issue. 

The reason I was having the system("pause") is because it was a good way of being able to run the project exe via visual studio and have the command window stay open at the end until the user presses a key.
