### ISSUE TITLE
Don't discovery tests

### ISSUE THREAD

**Issue by clabnet** [JohnnyHendriks/TestAdapter_Catch2#50]
Hi, 
using [this ](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/ReferenceTests/ReferenceTests.runsettings) referencetest anyone test of the  [libcron](https://github.com/PerMalmberg/libcron)  application is not discovered using VS2019.
Any suggestion please ? Thank's

**Comment by JohnnyHendriks** [comment]
Hi,
the `runsettings`-file you tried is intended to demonstrate the possibility to use your own custom test discovery mechanism as described [here](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Discovery.md). However, you are using the default from Catch2. Removing the [`<DiscoverCommandLine>`](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#discovercommandline)-parameter from the file, and as such using the default setting for this parameter (`--verbosity high --list-tests *`) should solve your problem. Here I assume you adjusted the [`<FilenameFilter>`](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#filenamefilter)-parameter for your situation.

Alternatively you can use the following minimal `runsettings`-file, that has been adapted to suit the project you linked to. Essentially you only need to set an appropriate regex for the [`<FilenameFilter>`](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#filenamefilter) setting to uniquely identify your test executables, and keep default values for the other parameters to make things work.

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>

  <Catch2Adapter>
    <FilenameFilter>^cron_test</FilenameFilter>
  </Catch2Adapter>

</RunSettings>
```

Hope this helps.
