### ISSUE TITLE
"invalid discovery commandline" when argument does not start with dash

### ISSUE THREAD

**Issue by Shadorc** [JohnnyHendriks/TestAdapter_Catch2#54]
Hello,

I'm trying to use this extension on an executable that gives arguments to Catch2 only when the command line contains "/unittest"
For example:
`myexe.exe /unittest --verbosity high --list-tests *`
The discovery command line should be:
`<DiscoverCommandLine>/unittest --verbosity high --list-tests *</DiscoverCommandLine>`

But I can't do this because Catch2 Test adapter uses a regex to check that every arguments matches `--<arg>` or `-<arg>`.
I can't really change the way my executable parses argument because it is a production tool already widely used.

Is there any fix for this?

Thanks for your help

**Comment by ScottHutchinson** [comment]
What we did was to filter out all the non-Catch2 arguments before passing the rest of the arguments to Catch2. We also added new command line parameters to our app like --test to run the tests and --silent and --hidden to prevent the app from showing dialogs or windows during the tests, which speeds up the tests and prevents them from stopping before they finish.

I suppose another alternative might be to put your Catch2 tests in a separate executable, but that might have more problems accessing the objects under test if they aren't already exposed in a public API.

**Comment by JohnnyHendriks** [comment]
@Shadorc . I assume the same commandline prefix is needed when running the tests. As the test execution commandline that is used is effectively an implementation detail, it is not configurable. I have not encountered your use case before, but I could add a setting to allow a `CommandLinePrefix` to be pre-pended to any commandline argument that is used to start a Catch2 process. Do you think that would solve your problem?

**Comment by Shadorc** [comment]
@JohnnyHendriks Hello, thanks for your suggestion! This would effectively solve my issue but I was finally able to manage our command line implementation and change it to support this extension without too many breaking changes, so I do not need this change anymore.
However, I'm now encountering an other issue, `--list-tests --verbosity high` is returning
```
  UIString
    folder\tmp\blob\win64\Localization/..\..\..\..\..\pipeline\packages\
    system\Localization\src\localization\uistring_test.cpp(72)
    (NO DESCRIPTION)
```
The filename is relative, and this extension is searching for an absolute path (looking at the regex, it seems to wait for the filename to start with `[A-Z]:\`) 
I don't think I can do anything on my side to change this due to the way it is implemented in Catch2. I'm also wondering if changing the regex would solve my issue, this path seems weird due to blob compilation, I'm not sure if visual studio would find it back even by changing the regex :/
