### ISSUE TITLE
Is there any way to run Catch2 from VS 2019 with CMake generator "Unix Makefiles"?

### ISSUE THREAD

**Issue by TimC0de** [JohnnyHendriks/TestAdapter_Catch2#55]
Hello, I want to configure tests via VS 2019 and I'm using Catch2.
I watch Walkthrough and googled answers to my questions, but I didn't find answer for my question.
I'm building for WSL2 using "Unix Makefiles" generator and "ctest" command from WSL itself works fine, but VS doesn't discover my tests.

Is there any solution for such case?
Can you please help me with that?

Thank you.

**Comment by JohnnyHendriks** [comment]
As far as I can tell this use case is not supported by Visual Studio at this moment. Based on the [Microsoft docs](https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022) support for this might come in a future version of Visual Studio.

**Comment by TimC0de** [comment]
Thank you for the answer
