### ISSUE TITLE
Visual Studio stuck when click test case

### ISSUE THREAD

**Issue by zhoujinhai** [JohnnyHendriks/TestAdapter_Catch2#57]
### question
The visual studio was stuck when I am click the test case

### envs
- Visual Studio:  2019 16.11.6
- TestAdapter_Catch2: 1.8.0

### details
I have writed the test.cpp, and follow the [Tutorial](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Walkthrough-vs2019.md) to use TestAdapter_Catch2, The windows shows the all test cases,  when I click the `io`, this two cases were runs， but when I click the `Fisrt` or `Second` the VS2019 has stuck.
```C++
#define CATCH_CONFIG_MAIN
#include <catch.hpp>

TEST_CASE("core::io::First", "[test]")
{
	int a = 1;
	REQUIRE(a == 1);
}

TEST_CASE("core::io::Second", "[test]")
{
	int a = 1;
	REQUIRE(a == 2);
}
```

![image](https://user-images.githubusercontent.com/20365125/155636247-76f8947b-d255-4b60-a2cc-ad362f530619.png)

**Comment by JohnnyHendriks** [comment]
I have tried to reproduce, but everything seems to work just fine on my machine. If the test executable works fine on the commandline for you, then it should work fine in the test explorer as well. Then again I'm using visual studio configured with the English language. As far as I can tell this seems to be a problem with Visual Studio to me and not with the test adapter. Sorry I cannot be of more help.
