### ISSUE TITLE
Merge with https://github.com/xkbeyer/CatchTestAdapter

### ISSUE THREAD

**Issue by fmuecke** [JohnnyHendriks/TestAdapter_Catch2#6]
There is another TestAdapter solution for Catch2: https://github.com/xkbeyer/CatchTestAdapter
Maybe you could get together and combine your solutions :-)

**Comment by JohnnyHendriks** [comment]
Thank you for this information. I was not aware of this project. I had a quick look and merging the solutions is probably going to be difficult due to the different approaches. But learning from each others approaches/implementations is definitely a possibility.
