### ISSUE TITLE
Feature Request: VS2022 Support

### ISSUE THREAD

**Issue by ajtrowell** [JohnnyHendriks/TestAdapter_Catch2#61]
I was able to setup the test adapter in just a few minutes on VS2019.  Works nicely.

Do you support VS2022, or plan to provide support?
I actually only tried VS2019 after spending an hour trying to set it up on VS2022 without any luck.

**Comment by JohnnyHendriks** [comment]
Support for VS2022 was added almost a year ago. Setup should be the same as for VS2019. I typically install it via the Manage Extension feature in Visual Studio via the Visual Studio Marketplace. I've been using it successfully in VS2022 for a long time already. Just make sure to use an appropriate `runsettings`-file. Following the steps described in the [VS2019 walkthrough](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Walkthrough-vs2019.md) should also work for VS2022.
