### ISSUE TITLE
Is there any maximum limit to scenario name

### ISSUE THREAD

**Issue by sundarsabapathi** [JohnnyHendriks/TestAdapter_Catch2#67]
I am using Catch2 version 3.2.1. I have the following scenarios in my test

```
SCENARIO("Process CIM event received when an active transaction is completed successfully or rolled back")
{
         ..........
         ..........
}

SCENARIO("Process CIM event received when an active transaction is not completed successfully or rolled back")
{
         ...........
          ...........
}

SCENARIO("Process CIM event received when an active transaction is not completed until the maximum configured period")
{
        ..............
        ..............
}

```
The above scenarios names are unique but when I run the tests it shows 6 warning about the above scenario names.

```
[[DUPLICATE 1>>.Scenario: Process CIM event received when an active transaction is not
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.


completed successfully or rolled back
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.

completed until the maximum configured period
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.


Scenario: Process CIM event received when an active transaction is completed
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.


Scenario: Process CIM event received when an active transaction is not
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.


successfully or rolled back
 No source available

 Message: 
Testcase could not be run. Probably the used testcase name is the cause. Change the testcase name and try again. Typically, this problem is encountered when the last character of the testcase name is a space.
```

Looks it trim the description suffix and compare the each scenario name and consider it as duplicated. How can I solve this warnings?

**Comment by sundarsabapathi** [comment]
I execute my tests using "test.exe" with the parameter "--list-tests" it prints the below output in the console

```
Scenario: Process CIM event received when an active transaction is completed
  successfully or rolled back
Scenario: Process CIM event received when an active transaction is not
  completed successfully or rolled back
Scenario: Process CIM event received when an active transaction is not
  completed until the maximum configured period
```
Is this above output cause the reason for warnings highlighted in the test explorer ?

**Comment by JohnnyHendriks** [comment]
Hi, have you configured a `<DiscoverCommandLine>` in your `.runsettings` file?
If so this could explain your problem. In Catch2 version 3.x.x the output from a regular `--list-tests` call with a default reporter has changed slightly, making it impossible to determine when a test case name rolls over to the next line. Luckily this can be circumvented by using `--verbosity high --list-tests --reporter xml *` as `<DiscoverCommandLine>` (which is the default if you do not supply your own). The `--verbosity high` part is only useful for use with version 2.x.x of Catch2 and should not be needed in your case as long as you use the `--reporter xml` part (which is ignored for version 2.x.x of Catch2).

**Comment by horenmar** [comment]
Technically you can tell when a test name rolled over by the indentation. But yeah, you should be using XML output if available.

**Comment by sundarsabapathi** [comment]
Thanks @JohnnyHendriks for your quick reply. Yes I am configured `<DiscoverCommandLine>` in my .`runsettings` file. Like this
`<DiscoverCommandLine>--list-tests *</DiscoverCommandLine>` after I follow your suggestion to update in the .`runsettings` file  `<DiscoverCommandLine>--list-tests --reporter xml*</DiscoverCommandLine>` it works as expected no warning highlighted in test explorer. Again big thanks to both of you @JohnnyHendriks and @horenmar

**Comment by JohnnyHendriks** [comment]
@horenmar. FYI, in Catch2 version 3.x, the indentation for the rolled over test case name was lost. I know because I have tests for rendering that output that fail if used with Catch2 v3.x. So if this wasn't a conscious decision, it would be a regression I guess. That being said, using the xml reporter for discovery is far superior, at least from a tooling point of view. So thank you for that one.

**Comment by horenmar** [comment]
> FYI, in Catch2 version 3.x, the indentation for the rolled over test case name was lost

That's intentional actually. The goal of the change was to make it so that you can tell by the indentation whether given text is part of test name vs tag vs fileloc.

Upon closer inspection, this does cause issues with untagged test cases combined with non-high verbosity:

**default verbosity**
```
  Parse uints
      [parse-numbers]
  Tracker
  Our PCG implementation provides expected results for known seeds
      [rng]
  Comparison ops
      [rng]
```

**high verbosity**
```
  Parse uints
    /mnt/c/ubuntu/Catch2/tests/SelfTest/IntrospectiveTests/Parse.tests.cpp:13
      [parse-numbers]
  Tracker
    /mnt/c/ubuntu/Catch2/tests/SelfTest/IntrospectiveTests/PartTracker.tests.
    cpp:22
  Our PCG implementation provides expected results for known seeds
    /mnt/c/ubuntu/Catch2/tests/SelfTest/IntrospectiveTests/
    RandomNumberGeneration.tests.cpp:14
      [rng]
```

(Before there was ambiguity between line break on a name and the source loc)


But, uh, between the fact that it is simple enough to force all tests to have at least one tag (`-#`) and that people should be using the structured listing output, I don't care about the ambiguity.
