### ISSUE TITLE
MSVS2022 tests not discovered

### ISSUE THREAD

**Issue by aPSopt** [JohnnyHendriks/TestAdapter_Catch2#69]
MSVS2022
Catch2 installed via vcpkg
Created default console c++ msvs project
Created default test from Catch2 tutorial -> it executed fine, all displayed fine in console window
Saved _Minimal.runsettings_ from [tutorial](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Walkthrough-vs2019.md) + edit _FilenameFilter_ for correct search
Do "Clean solution" + "Build solution"

As a result: **test not found** in .exe.
In test output I see followed information:
```
Log level is set to Informational (Default).
Source code repository not available. Some features may not work as expected.
Connected to test environment '< Local Windows Environment >'
Test data store opened in 0,029 sec.
========== Starting test discovery ==========
Started Catch2Adapter test discovery...
Finished Catch2Adapter test discovery.
No test is available in C:\D\TMP\DeleteThis\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 981,3 ms ==========

```

Can it be fixed?

Every year I try this adapter and every year it not works with minimal+default+standard code :(
I tried on different machines with different visual studios and I don't have any cases where it works.
I think you should test your utility at least on default minimal Catch2 project.

**Comment by JohnnyHendriks** [comment]
Sorry to hear you are having problems getting the Test Adapter to work for you. I have extensive tests that I run for each version of Catch2 that has been released. So I'm convinced that the test adapter should work. I work with it myself on a daily basis.

You can try the following to help with diagnosing the problem.
- Run the test executable with the following commandline `--verbosity high --list-tests --reporter xml *`. This should result in  output that describes all tests in your test executable. These are the default cli-parameters that are used by the test adapter.
- If that works fine, disabling the `GoogleTest` and `BoostTest` extensions may help. These are typically installed by default, and have been known to interfere with Catch2 test discovery.
- Add `<Logging>verbose</Logging>` or `<Logging>debug</Logging>` to the `<Catch2Adapter>` settings in the  `.runsettings`-file. This will give more information of what the Test Adapter for Catch2 is doing and as such may give a hint of what is going wrong.

Not much more I can do for you at this time I'm afraid based on the provided information.

**Comment by juangburgos** [comment]
Me too:
```
========== Test discovery finished: 0 Tests found in 1.8 sec ==========
No tests found to run.
Connected to test environment '< Local Windows Environment >'
No tests found to run.
Building Test Projects
Executing all tests in project: evtests
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Building Test Projects
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Building Test Projects
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
========== Starting test discovery ==========
No test is available in C:\Users\admin\Desktop\REPOS\test\tests.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 915.6 ms ==========
```
Command Arguments: `--verbosity high --list-tests --reporter xml *`

`./.runsettings`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>

  <!-- Adapter Specific sections -->
  <Catch2Adapter>
    <Logging>verbose</Logging>
    <FilenameFilter>.*</FilenameFilter>
    <!-- Regex filter -->
  </Catch2Adapter>

</RunSettings>
```

**Comment by juangburgos** [comment]
Disabling gtest extrension, cleaning everything up and regenerating the solution helped, in case somebody has the same issue

**Comment by aPSopt** [comment]
I have followed situation:

- 
> Run the test executable with the following commandline --verbosity high --list-tests --reporter xml *. 
I received followed:
```
<?xml version="1.0" encoding="UTF-8"?>
<MatchingTests>
  <TestCase>
    <Name>Factorials are computed</Name>
    <ClassName/>
    <Tags>[factorial]</Tags>
    <SourceInfo>
      <File>C:\TMP\DeleteThis\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp</File>
      <Line>33</Line>
    </SourceInfo>
  </TestCase>
</MatchingTests>
```
It look fine - it found test case fine

- 
> disabling the GoogleTest and BoostTest extensions may help

I disabled both of them

- 
> Add <Logging>verbose</Logging> or <Logging>debug</Logging> to the <Catch2Adapter> settings in the .runsettings-file.

Here my .runsettings file:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <MaxCpuCount>4</MaxCpuCount>
    <TestSessionTimeout>60000</TestSessionTimeout><!-- Milliseconds -->
  </RunConfiguration>

  <!-- Adapter Specific sections -->

  <!-- Catch2 adapter -->
  <Catch2Adapter disabled="false">
    <DebugBreak>on</DebugBreak>
    <DiscoverCommandLine>--discover *</DiscoverCommandLine><!-- Note this custom discoverer is not part of the Catch2 framework -->
    <DiscoverTimeout>500</DiscoverTimeout>
    <FilenameFilter>ConsoleApplication1.exe</FilenameFilter>
    <IncludeHidden>true</IncludeHidden>
    <Logging>Verbose</Logging>
    <MessageFormat>StatsOnly</MessageFormat>
    <StackTraceFormat>ShortInfo</StackTraceFormat>
    <StackTracePointReplacement>,</StackTracePointReplacement>
    <TestCaseTimeout>20000</TestCaseTimeout><!-- Milliseconds -->
    <WorkingDirectory></WorkingDirectory>
    <WorkingDirectoryRoot>Executable</WorkingDirectoryRoot>
  </Catch2Adapter>

</RunSettings>
```

Next I do "clean solution", "build solution" and received followed log:
```
========== Starting test discovery ==========
Started Catch2Adapter test discovery...
Discover log:
Source: C:\TMP\DeleteThis\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe
  Invalid source.

Finished Catch2Adapter test discovery.
No test is available in C:\TMP\DeleteThis\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 748 ms ==========
```

Catch2Adapter found correct path to .exe but can't find any tests.

Do you have any suggestions in this case?

**Comment by JohnnyHendriks** [comment]
I see you are using a custom `<DiscoverCommandLine>` setting. If you did not do anything special for you test executable to enable this setting, that would explain why discovery fails. I would suggest to delete that setting from the `.runsettings`-file. This will then ensure you are using the default discovery setting, which should work unless you did something very special for your test executable.

**Comment by aPSopt** [comment]
Ok, I delete it and here my .runsettings file now:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <MaxCpuCount>4</MaxCpuCount>
    <TestSessionTimeout>60000</TestSessionTimeout><!-- Milliseconds -->
  </RunConfiguration>

  <!-- Adapter Specific sections -->

  <!-- Catch2 adapter -->
  <Catch2Adapter disabled="false">
    <DebugBreak>on</DebugBreak>
    <DiscoverTimeout>500</DiscoverTimeout>
    <FilenameFilter>ConsoleApplication1.exe</FilenameFilter>
    <IncludeHidden>true</IncludeHidden>
    <Logging>Verbose</Logging>
    <MessageFormat>StatsOnly</MessageFormat>
    <StackTraceFormat>ShortInfo</StackTraceFormat>
    <StackTracePointReplacement>,</StackTracePointReplacement>
    <TestCaseTimeout>20000</TestCaseTimeout><!-- Milliseconds -->
    <WorkingDirectory></WorkingDirectory>
    <WorkingDirectoryRoot>Executable</WorkingDirectoryRoot>
  </Catch2Adapter>

</RunSettings>
```

Then I do clean and build. Received result:
```
========== Starting test discovery ==========
Started Catch2Adapter test discovery...
Discover log:
Source: C:\TMP\DeleteThis\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe
  Invalid source.

Finished Catch2Adapter test discovery.
No test is available in C:\TMP\DeleteThis\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 982,4 ms ==========
```

It doesn't works. 
Do you have any suggestions in this case?

**Comment by JohnnyHendriks** [comment]
Looks like you added the filename extension to the `<FilenameFilter>`, this is most likely causing the problem as the name matching is done on the filename without extension. Setting that value to `ConsoleApplication1` instead of `ConsoleApplication1.exe`, should solve your problem in this case. See [documentation for the FilenameFilter parameter](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/main/Docs/Settings.md#filenamefilter)  for more info.

**Comment by aPSopt** [comment]
Ok, now it works, thanks!
