### ISSUE TITLE
New Release, Catch2 v3.4.0 support?

### ISSUE THREAD

**Issue by TibRib** [JohnnyHendriks/TestAdapter_Catch2#72]
Hello JohnnyHendriks,
Do you plan on making a new release ? The last one traces back to January 2022.
I'm also seeing you've added support for newer Catch versions and made several commits in april 2023.
Could you make a new one ?

Thank you for the test adapter 👍

**Comment by TibRib** [comment]
I've built 1.8.5 and everything ran fine on my end at least. Tested with Catch 3.4.0 without problems.

**Comment by JohnnyHendriks** [comment]
I'm currently working on the documentation for the next version which will be 2.0 due to major new features becoming available that require more complicated configuration of the `.runsettings`-file. Hope to release the new version coming weekend.

**Comment by JohnnyHendriks** [comment]
New version of Test Adapter for Catch 2 has been released.

**Comment by TibRib** [comment]
Great ! Thank you for the release, 
Happy end of the year / christmas
